/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type NewIntentStruct = {
  intentId: BigNumberish;
  srcUser: AddressLike;
  dstUser: string;
  dstChainId: BigNumberish;
  tokenIn: AddressLike;
  amountIn: BigNumberish;
  tokenOut: string;
  amountOut: BigNumberish;
  timeout: BigNumberish;
  aiAgent: boolean;
};

export type NewIntentStructOutput = [
  intentId: bigint,
  srcUser: string,
  dstUser: string,
  dstChainId: bigint,
  tokenIn: string,
  amountIn: bigint,
  tokenOut: string,
  amountOut: bigint,
  timeout: bigint,
  aiAgent: boolean
] & {
  intentId: bigint;
  srcUser: string;
  dstUser: string;
  dstChainId: bigint;
  tokenIn: string;
  amountIn: bigint;
  tokenOut: string;
  amountOut: bigint;
  timeout: bigint;
  aiAgent: boolean;
};

export interface EscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ETH_ADDRESS"
      | "agentFlatFee"
      | "agentPercentFee"
      | "cancelIntent"
      | "changeOwner"
      | "defaultFlatFee"
      | "defaultPercentFee"
      | "escrowFunds"
      | "executeCall"
      | "finalizeAuction"
      | "intentChainId"
      | "intents"
      | "owner"
      | "setFees"
      | "solveIntentLocal"
      | "solveIntentRemote"
      | "unlockSolverFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CanceledIntent"
      | "EscrowedFunds"
      | "FinalizedAuction"
      | "SolvedIntentLocal"
      | "SolvedIntentRemote"
      | "UnlockedSolverFunds"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ETH_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentFlatFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentPercentFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelIntent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFlatFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPercentFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrowFunds",
    values: [NewIntentStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executeCall",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "intentChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "intents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "solveIntentLocal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "solveIntentRemote",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockSolverFunds",
    values: [BigNumberish, BigNumberish, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ETH_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentFlatFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentPercentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultFlatFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPercentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intentChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "solveIntentLocal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solveIntentRemote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockSolverFunds",
    data: BytesLike
  ): Result;
}

export namespace CanceledIntentEvent {
  export type InputTuple = [intentId: BigNumberish];
  export type OutputTuple = [intentId: bigint];
  export interface OutputObject {
    intentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowedFundsEvent {
  export type InputTuple = [intentId: BigNumberish];
  export type OutputTuple = [intentId: bigint];
  export interface OutputObject {
    intentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizedAuctionEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    solver: AddressLike,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    solver: string,
    amountOut: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    solver: string;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolvedIntentLocalEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    solver: AddressLike,
    dstUser: AddressLike,
    tokenIn: AddressLike,
    amountIn: BigNumberish,
    tokenOut: AddressLike,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    solver: string,
    dstUser: string,
    tokenIn: string,
    amountIn: bigint,
    tokenOut: string,
    amountOut: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    solver: string;
    dstUser: string;
    tokenIn: string;
    amountIn: bigint;
    tokenOut: string;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolvedIntentRemoteEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    srcChainId: BigNumberish,
    dstUser: AddressLike,
    tokenOut: AddressLike,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    srcChainId: bigint,
    dstUser: string,
    tokenOut: string,
    amountOut: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    srcChainId: bigint;
    dstUser: string;
    tokenOut: string;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedSolverFundsEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    solver: AddressLike,
    tokenIn: AddressLike,
    amountIn: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    solver: string,
    tokenIn: string,
    amountIn: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    solver: string;
    tokenIn: string;
    amountIn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escrow extends BaseContract {
  connect(runner?: ContractRunner | null): Escrow;
  waitForDeployment(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ETH_ADDRESS: TypedContractMethod<[], [string], "view">;

  agentFlatFee: TypedContractMethod<[], [bigint], "view">;

  agentPercentFee: TypedContractMethod<[], [bigint], "view">;

  cancelIntent: TypedContractMethod<
    [intentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  defaultFlatFee: TypedContractMethod<[], [bigint], "view">;

  defaultPercentFee: TypedContractMethod<[], [bigint], "view">;

  escrowFunds: TypedContractMethod<
    [newIntent: NewIntentStruct],
    [bigint],
    "payable"
  >;

  executeCall: TypedContractMethod<
    [target: AddressLike, data: BytesLike, value: BigNumberish],
    [string],
    "nonpayable"
  >;

  finalizeAuction: TypedContractMethod<
    [intentId: BigNumberish, solver: AddressLike, amountOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  intentChainId: TypedContractMethod<[], [bigint], "view">;

  intents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        srcUser: string;
        dstUser: string;
        srcChainId: bigint;
        dstChainId: bigint;
        tokenIn: string;
        amountIn: bigint;
        tokenOut: string;
        amountOut: bigint;
        solver: string;
        timeout: bigint;
        aiAgent: boolean;
        refundAmount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setFees: TypedContractMethod<
    [
      _defaultFlatFee: BigNumberish,
      _agentFlatFee: BigNumberish,
      _defaultPercentFee: BigNumberish,
      _agentPercentFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  solveIntentLocal: TypedContractMethod<
    [intentId: BigNumberish],
    [void],
    "payable"
  >;

  solveIntentRemote: TypedContractMethod<
    [
      intentId: BigNumberish,
      srcChainId: BigNumberish,
      tokenOut: AddressLike,
      amountOut: BigNumberish,
      dstUser: AddressLike
    ],
    [void],
    "payable"
  >;

  unlockSolverFunds: TypedContractMethod<
    [
      intentId: BigNumberish,
      srcChainId: BigNumberish,
      dstUser: string,
      tokenOut: string,
      amountOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ETH_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentFlatFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentPercentFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelIntent"
  ): TypedContractMethod<[intentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultFlatFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultPercentFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrowFunds"
  ): TypedContractMethod<[newIntent: NewIntentStruct], [bigint], "payable">;
  getFunction(
    nameOrSignature: "executeCall"
  ): TypedContractMethod<
    [target: AddressLike, data: BytesLike, value: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeAuction"
  ): TypedContractMethod<
    [intentId: BigNumberish, solver: AddressLike, amountOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "intentChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        srcUser: string;
        dstUser: string;
        srcChainId: bigint;
        dstChainId: bigint;
        tokenIn: string;
        amountIn: bigint;
        tokenOut: string;
        amountOut: bigint;
        solver: string;
        timeout: bigint;
        aiAgent: boolean;
        refundAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [
      _defaultFlatFee: BigNumberish,
      _agentFlatFee: BigNumberish,
      _defaultPercentFee: BigNumberish,
      _agentPercentFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "solveIntentLocal"
  ): TypedContractMethod<[intentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "solveIntentRemote"
  ): TypedContractMethod<
    [
      intentId: BigNumberish,
      srcChainId: BigNumberish,
      tokenOut: AddressLike,
      amountOut: BigNumberish,
      dstUser: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "unlockSolverFunds"
  ): TypedContractMethod<
    [
      intentId: BigNumberish,
      srcChainId: BigNumberish,
      dstUser: string,
      tokenOut: string,
      amountOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CanceledIntent"
  ): TypedContractEvent<
    CanceledIntentEvent.InputTuple,
    CanceledIntentEvent.OutputTuple,
    CanceledIntentEvent.OutputObject
  >;
  getEvent(
    key: "EscrowedFunds"
  ): TypedContractEvent<
    EscrowedFundsEvent.InputTuple,
    EscrowedFundsEvent.OutputTuple,
    EscrowedFundsEvent.OutputObject
  >;
  getEvent(
    key: "FinalizedAuction"
  ): TypedContractEvent<
    FinalizedAuctionEvent.InputTuple,
    FinalizedAuctionEvent.OutputTuple,
    FinalizedAuctionEvent.OutputObject
  >;
  getEvent(
    key: "SolvedIntentLocal"
  ): TypedContractEvent<
    SolvedIntentLocalEvent.InputTuple,
    SolvedIntentLocalEvent.OutputTuple,
    SolvedIntentLocalEvent.OutputObject
  >;
  getEvent(
    key: "SolvedIntentRemote"
  ): TypedContractEvent<
    SolvedIntentRemoteEvent.InputTuple,
    SolvedIntentRemoteEvent.OutputTuple,
    SolvedIntentRemoteEvent.OutputObject
  >;
  getEvent(
    key: "UnlockedSolverFunds"
  ): TypedContractEvent<
    UnlockedSolverFundsEvent.InputTuple,
    UnlockedSolverFundsEvent.OutputTuple,
    UnlockedSolverFundsEvent.OutputObject
  >;

  filters: {
    "CanceledIntent(uint256)": TypedContractEvent<
      CanceledIntentEvent.InputTuple,
      CanceledIntentEvent.OutputTuple,
      CanceledIntentEvent.OutputObject
    >;
    CanceledIntent: TypedContractEvent<
      CanceledIntentEvent.InputTuple,
      CanceledIntentEvent.OutputTuple,
      CanceledIntentEvent.OutputObject
    >;

    "EscrowedFunds(uint256)": TypedContractEvent<
      EscrowedFundsEvent.InputTuple,
      EscrowedFundsEvent.OutputTuple,
      EscrowedFundsEvent.OutputObject
    >;
    EscrowedFunds: TypedContractEvent<
      EscrowedFundsEvent.InputTuple,
      EscrowedFundsEvent.OutputTuple,
      EscrowedFundsEvent.OutputObject
    >;

    "FinalizedAuction(uint256,address,uint256)": TypedContractEvent<
      FinalizedAuctionEvent.InputTuple,
      FinalizedAuctionEvent.OutputTuple,
      FinalizedAuctionEvent.OutputObject
    >;
    FinalizedAuction: TypedContractEvent<
      FinalizedAuctionEvent.InputTuple,
      FinalizedAuctionEvent.OutputTuple,
      FinalizedAuctionEvent.OutputObject
    >;

    "SolvedIntentLocal(uint256,address,address,address,uint256,address,uint256)": TypedContractEvent<
      SolvedIntentLocalEvent.InputTuple,
      SolvedIntentLocalEvent.OutputTuple,
      SolvedIntentLocalEvent.OutputObject
    >;
    SolvedIntentLocal: TypedContractEvent<
      SolvedIntentLocalEvent.InputTuple,
      SolvedIntentLocalEvent.OutputTuple,
      SolvedIntentLocalEvent.OutputObject
    >;

    "SolvedIntentRemote(uint256,uint8,address,address,uint256)": TypedContractEvent<
      SolvedIntentRemoteEvent.InputTuple,
      SolvedIntentRemoteEvent.OutputTuple,
      SolvedIntentRemoteEvent.OutputObject
    >;
    SolvedIntentRemote: TypedContractEvent<
      SolvedIntentRemoteEvent.InputTuple,
      SolvedIntentRemoteEvent.OutputTuple,
      SolvedIntentRemoteEvent.OutputObject
    >;

    "UnlockedSolverFunds(uint256,address,address,uint256)": TypedContractEvent<
      UnlockedSolverFundsEvent.InputTuple,
      UnlockedSolverFundsEvent.OutputTuple,
      UnlockedSolverFundsEvent.OutputObject
    >;
    UnlockedSolverFunds: TypedContractEvent<
      UnlockedSolverFundsEvent.InputTuple,
      UnlockedSolverFundsEvent.OutputTuple,
      UnlockedSolverFundsEvent.OutputObject
    >;
  };
}
