//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Escrow
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const escrowAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  { type: 'fallback', stateMutability: 'payable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'ETH_ADDRESS',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'INTENT_CHAIN_ID',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'agentFlatFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'agentPercentFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'intentId', internalType: 'uint64', type: 'uint64' }],
    name: 'cancelIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_owner', internalType: 'address', type: 'address' }],
    name: 'changeOwner',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'defaultFlatFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'defaultPercentFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'newIntent',
        internalType: 'struct NewIntent',
        type: 'tuple',
        components: [
          { name: 'intentId', internalType: 'uint64', type: 'uint64' },
          { name: 'srcUser', internalType: 'address', type: 'address' },
          { name: 'dstUser', internalType: 'string', type: 'string' },
          { name: 'dstChainId', internalType: 'uint8', type: 'uint8' },
          { name: 'tokenIn', internalType: 'address', type: 'address' },
          { name: 'amountIn', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenOut', internalType: 'string', type: 'string' },
          { name: 'amountOut', internalType: 'uint256', type: 'uint256' },
          { name: 'timeout', internalType: 'uint256', type: 'uint256' },
          { name: 'aiAgent', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
    name: 'escrowFunds',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'target', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'executeCall',
    outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'intentId', internalType: 'uint64', type: 'uint64' },
      { name: 'solver', internalType: 'address', type: 'address' },
      { name: 'amountOut', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'finalizeAuction',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
    name: 'intents',
    outputs: [
      { name: 'srcUser', internalType: 'address', type: 'address' },
      { name: 'dstUser', internalType: 'string', type: 'string' },
      { name: 'srcChainId', internalType: 'uint8', type: 'uint8' },
      { name: 'dstChainId', internalType: 'uint8', type: 'uint8' },
      { name: 'tokenIn', internalType: 'address', type: 'address' },
      { name: 'amountIn', internalType: 'uint256', type: 'uint256' },
      { name: 'tokenOut', internalType: 'string', type: 'string' },
      { name: 'amountOut', internalType: 'uint256', type: 'uint256' },
      { name: 'solver', internalType: 'address', type: 'address' },
      { name: 'timeout', internalType: 'uint256', type: 'uint256' },
      { name: 'aiAgent', internalType: 'bool', type: 'bool' },
      { name: 'refundAmount', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '_defaultFlatFee', internalType: 'uint256', type: 'uint256' },
      { name: '_agentFlatFee', internalType: 'uint256', type: 'uint256' },
      { name: '_defaultPercentFee', internalType: 'uint256', type: 'uint256' },
      { name: '_agentPercentFee', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setFees',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'intentId', internalType: 'uint64', type: 'uint64' }],
    name: 'solveIntentLocal',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'intentId', internalType: 'uint64', type: 'uint64' },
      { name: 'srcChainId', internalType: 'uint8', type: 'uint8' },
      { name: 'tokenOut', internalType: 'address', type: 'address' },
      { name: 'amountOut', internalType: 'uint256', type: 'uint256' },
      { name: 'dstUser', internalType: 'address', type: 'address' },
    ],
    name: 'solveIntentRemote',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'intentId', internalType: 'uint64', type: 'uint64' },
      { name: 'srcChainId', internalType: 'uint8', type: 'uint8' },
      { name: 'dstUser', internalType: 'string', type: 'string' },
      { name: 'tokenOut', internalType: 'string', type: 'string' },
      { name: 'amountOut', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'unlockSolverFunds',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: true,
      },
    ],
    name: 'CanceledIntent',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: true,
      },
    ],
    name: 'EscrowedFunds',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: true,
      },
      {
        name: 'solver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amountOut',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'FinalizedAuction',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: true,
      },
      {
        name: 'solver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'dstUser',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenIn',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amountIn',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'tokenOut',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amountOut',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SolvedIntentLocal',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: true,
      },
      {
        name: 'srcChainId',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'dstUser',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenOut',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amountOut',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SolvedIntentRemote',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: true,
      },
      {
        name: 'solver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenIn',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amountIn',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'UnlockedSolverFunds',
  },
] as const

export const escrowAddress =
  '0xAF55771e9cd32F93532670Ef358c8703d598505C' as const

export const escrowConfig = { address: escrowAddress, abi: escrowAbi } as const
